from .misc import MISC_CLASS_MAPPINGS, MISC_NAME_MAPPINGS
from .promts import PROMPTS_CLASS_MAPPINGS, PROMPTS_NAME_MAPPINGS

WEB_DIRECTORY = "./js"

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(MISC_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MISC_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(PROMPTS_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PROMPTS_NAME_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
